server:
  port: 8083

# Enable eureka client in gateway
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    

spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: "true"
      routes:
        - id: fornecedor
          uri: lb://fornecedor
          predicates:
            - Path=/fornecedor/**
          filters:
            - RewritePath=/fornecedor/(?<segment>.*), /$\{segment}
        - id: loja
          uri: lb://loja
          predicates:
            - Path=/loja/**
          filters:
            - RewritePath=/loja/(?<segment>.*), /$\{segment}
