server:
  port: 8081 # A aplicação de Fornecedor responde na porta 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
