server:
  port: 8888
spring:
  profiles:
    active: native # Busca as configurações dentro do File Systems
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/microservice-repo
